### ISSUE TITLE
h264_vdpau decode error

### ISSUE THREAD

**Issue by zhengchengbin610** [avafinger/ffmpeg-3.3.4_cedrus264#1]
Hi friend ,
   I  have  use this ffmpeg-3.3.4-cedrus on my banana Pi board, complile source code . now  I write a program test h264_vdpau decode , and  can  find the decoder ,but  decode packet error ,
error attached is decode-error,  I  write the decode packet data to a h264 file , attached is test.h264, please tell me what happen ? mybe the start code is 00 00 01? 
![decode-error](https://user-images.githubusercontent.com/26518131/40818305-1f168d00-6589-11e8-9080-3aef3d146ace.png)

 
   
[test.h264.zip](https://github.com/avafinger/ffmpeg-3.3.4_cedrus264/files/2060808/test.h264.zip)

**Comment by avafinger** [comment]
Can you please post your source code for further analysis? And what exactly your program do and what should be the result.
Additional information is also needed:
a) Board model  used
b) Compiler version used

If you feel it is a bug you can always place a bug report on https://github.com/linux-sunxi/libcedrus

**Comment by zhengchengbin610** [comment]
Firstly, thanks a lot for your response.
a) Banana Pi  BPI-M1+ used
b) System used: Linux bpi-iot-ros-ai 3.4.112-sun7i #2 SMP PREEMPT Sat May 28 20:25:03 CST 2016 armv7l armv7l armv7l GNU/Linux
c) compiler version used:gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
d) compile ffmpeg configure: 
   ./configure --prefix=./tag_x86 --extra-cflags=-fPIC -I/usr/include -I/usr/local/include --sysroot= --extra-ldflags=-Wl,-rpath-link=/usr/lib -L/usr/lib -L/usr/local/lib -gl -lc -lm -ldl --cross-prefix= --enable-static --disable-everything --disable-neon --enable-gpl --enable-vdpau --disable-shared --disable-hwaccels --enable-hwaccel=h264_vdpau --enable-bsf=h264_mp4toannexb --enable-bsf=aac_adtstoasc --enable-decoder=h264_vdpau --enable-decoder=aac --enable-decoder=pcm_s16le --enable-decoder=pcm_s16le_planar --enable-muxer=h264 --enable-muxer=mp4 --enable-demuxer=aac --enable-demuxer=mov --enable-encoder=aac --enable-protocol=file --enable-network --enable-parser=h264 --enable-parser=aac --enable-ffmpeg --disable-ffplay --disable-ffserver --disable-ffprobe --disable-avdevice --enable-avfilter --enable-swscale --enable-avcodec --enable-swresample --enable-avformat --enable-avresample --enable-debug --disable-stripping --enable-pthreads --disable-doc --disable-symver --enable-x86asm


please point me what and  where i wrong, thanks.

**Comment by zhengchengbin610** [comment]
@avafinger  Thank you vary much.  my problem was fixed . 
 Best Regard.

**Comment by avafinger** [comment]
@zhengchengbin610 ,

Please, can you point where you fixed it and close the issue?. BR

**Comment by zhengchengbin610** [comment]
Hi，my old source code not use the gpu decode mode ,so  i modify it to gpu accelerate mode.
