### ISSUE TITLE
aarch64

### ISSUE THREAD

**Issue by EhsanVahab** [avafinger/ffmpeg-3.3.4_cedrus264#3]
Hi dear @avafinger 
thanks for your great job.
is it necessary to install  uboborov/sunxi-cedar-mainline ?
what about the kernel and driver? whether I have to build legacy kernel or not?

**Comment by avafinger** [comment]
This ffmpeg is for kernel 3.1x (BSP) and will not work on the mainline kernel.
if you want to work with the mainline kernel you have to port uboborov's code to aarch64 if he has not done it yet.

**Comment by EhsanVahab** [comment]
> This ffmpeg is for kernel 3.1x (BSP) and will not work on the mainline kernel. if you want to work with the mainline kernel you have to port uboborov's code to aarch64 if he has not done it yet.

Thanks for your quick response.
uboborov has not done yet.
dear Avafinger, do you know whether there is any hardware encoder on Allwinner H5 or not?for H264/265 or any other codec.
I need to compress some images whit lowest cpu usage

**Comment by avafinger** [comment]
> there is any hardware encoder on Allwinner H5 or not?for H264/265

I do believe if you install kernel 3.10.y (BSP) this will work, but you get basic h264 compression. Forget about h265.
I have 4.19.y which has h264/h265 encoding on rk3399 (rockchip platform), if you really need hw encoding and can afford the higher cost.

**Comment by EhsanVahab** [comment]
> > there is any hardware encoder on Allwinner H5 or not?for H264/265
> 
> I do believe if you install kernel 3.10.y (BSP) this will work, but you get basic h264 compression. Forget about h265. I have 4.19.y which has h264/h265 encoding on rk3399 (rockchip platform), if you really need hw encoding and can afford the higher cost.

I'm not as experienced as you. sorry for my basic questions. and thanks for your clear responses.
